### ISSUE TITLE
Profile pictures not included in UserProfile

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura-CredentialsFacebook#28]
`UserProfile.photos` is always `nil` for me.

I have two public profile pictures on Facebook. The Facebook login page does mention my profile pictures will be made available to my app but they never make it there.

I have tried setting a breakpoint on `createUserProfile` in `Utils.swift` and noticed the `facebookData` dictionary only contains `id` and `name`.

How do I get the pictures as well?

**Comment by svanimpe** [comment]
Update: adding `options: ["fields": "name,picture"]` does the trick. This is really confusing as Facebook's documentation says `picture` is included with `public_profile`: https://developers.facebook.com/docs/facebook-login/permissions#reference-public_profile

Is this a bug on their end?

**Comment by quanvo87** [comment]
This is not a bug on Facebook's end. While `picture` is indeed included with `public_profile` by default, the data we are receiving from an `authenticate` request is not the entire `public_profile` object. Without any additional `fields` set, `authenticate` only returns an `id` and `name`. Any additional data will have to be specified as you did. Admittedly this is confusing.

**Comment by svanimpe** [comment]
Even more confusing because the documentation pages I read were referenced in the source code: https://github.com/IBM-Swift/Kitura-CredentialsFacebook/blob/master/Sources/CredentialsFacebook/CredentialsFacebookOptions.swift and I just went from there :)
