### ISSUE TITLE
Using Facebook web login with custom domain

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura-CredentialsFacebook#32]
Now that my app has a custom domain name, I am lost as to how to get Facebook web login working again.

I currently configure my `credentials` middleware as follows:

```
let credentials = Credentials()    
let facebook = CredentialsFacebook(clientId: Secrets.facebookAppID,
                                   clientSecret: Secrets.facebookAppSecret,
                                   callbackUrl: "\(configuration.url)/authentication/signin/callback",
                                   options: ["fields": "name,picture.type(large)"])
credentials.register(plugin: facebook)
credentials.options["failureRedirect"] = "/authentication/welcome"
```
`configuration` is a `ConfigurationManager` instance.

This works fine on localhost and when using `mybluemix.net` but this doesn't work when I access my app through `www.mydomain.com`.

`configuration.url` uses `mybluemix.net`, but even when I manually set the `callbackUrl` to use `mydomain.com`, things still don't work, meaning I get a `Cannot GET /authentication/signin/callback` response, with no errors in the log.

All callback URLs (including `mydomain.com`) are in the allowed list on Facebook. W.r.t. DNS settings, I have a CNAME record pointing `www.mydomain.com` to `myapp-mybluemix.net`.

**Comment by shmuelk** [comment]
When the browser is showing you the FaceBook login page, there should be a URL encoded as one of the query parameters of the IRL. What is it?

**Comment by svanimpe** [comment]
The URL I see when Facebook's dialog shows up is:
`https://www.facebook.com/dialog/oauth?client_id=myid&redirect_uri=https://aroundthetable.eu-gb.mybluemix.net/authentication/signin/callback&response_type=code`

When I click "Continue" there, I get redirected to:
`https://aroundthetable.eu-gb.mybluemix.net/authentication/signin/callback?code=AQBNZG6DwB2fCeR7le3JGomASQl7zCx35BpBuWcv0iT8VdHJRtRE5EIxD9cnilyvk2a358rsloaIpIdIVP8iWN8oZlYniJpZI-_QrGVFOwDxBAbGewtUPp7Q4HnA5E1jCiVHE5o35YZK4qNTvGtfWOjJf_KLAQek4BAL48OJuVkzp6xIXu3kBrCAeKPk3-yfvIK7SrTBAeitS8fZLPcXgHcGVfh18M2c055wAA0M02QbUHP1jyvUugkrkIeIExLbBbtInbC2dPuw_zUaBkRtenn88ls60-qpFP_rRUysf49zjy44aW4b2TKCdT3SnHBfMvA#_=_`

And then I get a `Cannot GET ...` response.

**Comment by svanimpe** [comment]
Note that I started on `mydomain.com/authentication/welcome`. The "Sign in with Facebook" button on that page sends a GET to the handler returned by `credentials.authenticate(credentialsType: facebook.name)`.

**Comment by svanimpe** [comment]
This turned out to be a simple cookie/session issue. Because the app was using two domains, there were two cookies/sessions in play. When using the custom domain, the situation was as follows:
- The Credentials middleware records the `returnTo` address in a session for the custom domain.
- A Facebook Web Login flow starts. The Facebook callback URL uses the mybluemix.net domain, so a session for that domain is used to store the user profile. The app then searches this session for a `returnTo` address, which is not found, as that was stored in a session for the custom domain.

Because there is no way to set that callback URL dynamically (it is configured once when the app starts), I solved this problem by fixing the callback URL to my custom domain and forwarding all requests to that custom domain. I used the following middleware for that:
```
struct ForwardingMiddleware: RouterMiddleware {
    
    func handle(request: RouterRequest, response: RouterResponse, next: @escaping () -> Void) throws {
        guard request.hostname != "localhost" else {
            next()
            return
        }
        if let customDomainName = Settings.customDomainName, request.hostname != customDomainName {
            try response.redirect("https://\(customDomainName)/")
        } else if let proto = request.headers["X-Forwarded-Proto"], proto == "http" {
            // Bluemix terminates SSL at the proxy level so we have to check the `X-Forwarded-Proto` header, not the URL.
            try response.redirect(request.originalURL.replacingOccurrences(of: "http://", with: "https://"))
        }
        next()
    }
}
```
This middleware checks if there is a custom domain set and if so, forwards all requests to it. It also enforces https.
